model_path: ./ResNet50_vd_infer/ResNet50_vd_infer.onnx
output_folder: ./ResNet50_vd_infer
mean:
  -
    - 0
    - 0
    - 0
std:
  -
    - 1
    - 1
    - 1
outputs: []
outputs_nodes: []
do_quantization: False
dataset:
