mean:
  - 0
  - 0
  - 0
std:
  - 1
  - 1
  - 1
model_path: ./yolov8_n_500e_coco/yolov8_n_500e_coco_wo_nms.onnx
outputs_nodes:
do_quantization: True
dataset: "./yolov8_n_500e_coco/dataset.txt"
output_folder: "./yolov8_n_500e_coco"
