mean:
  -
    - 123.675
    - 116.28
    - 103.53
std:
  -
    - 58.395
    - 57.12
    - 57.375
model_path: ./PPOCRV3_det_QAT/PPOCRV3_det_QAT.onnx
outputs_nodes:
do_quantization: False
dataset:
output_folder: "./PPOCRV3_det_QAT"
