name: Build
on: [push, pull_request]

jobs:
  macOS-latest-cpp:
    runs-on: macOS-latest

    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Build FastDeploy
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_ORT_BACKEND=ON -DENABLE_PADDLE_BACKEND=ON -DENABLE_OPENVINO_BACKEND=ON -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk -DENABLE_VISION=ON -DENABLE_TEXT=ON
          make -j12
          make install
          ls -l
  macOS-latest-py:
    runs-on: macos-latest

    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Get Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build FastDeploy
        working-directory: ./python
        run: |
          export ENABLE_ORT_BACKEND=ON
          export ENABLE_PADDLE_BACKEND=ON
          export ENABLE_OPENVINO_BACKEND=ON
          export ENABLE_VISION=ON
          export ENABLE_TEXT=ON
          
          python setup.py build
          python setup.py bdist_wheel
          ls -l
